### ISSUE TITLE
添加个动漫就更好了！

### ISSUE THREAD

**Issue by KingBoomBoom** [cuifengcn/TAICHI-flet#1]
如果里面再添加了动漫就更好了 然后 搜索到的种子怎么获取到，求告知

**Comment by cuifengcn** [comment]
> 如果里面再添加了动漫就更好了 然后 搜索到的种子怎么获取到，求告知

可以考虑。种子点击”复制“，然后在迅雷等软件打开

**Comment by cuifengcn** [comment]
已添加
