### ISSUE TITLE
requirement.txt建议更新下flet版本

### ISSUE THREAD

**Issue by pbj0718** [cuifengcn/TAICHI-flet#12]
flet版本0.2.0-dev859不存在，查看了下官网没有了，国内其他的镜像源使用pip install指定版本的话也不行
![image](https://user-images.githubusercontent.com/46159479/211757791-aa8adbac-41de-417e-897f-8e992e1f2c0c.png)

**Comment by pbj0718** [comment]
国内相关其他的镜像源也尝试了，pip install的话找不到

**Comment by txwx** [comment]
用最新版的也没问题，我试过了,requirement.txt这里面的内容你可以改
