### ISSUE TITLE
能在macOS下运行吗？

### ISSUE THREAD

**Issue by k2y1982** [cuifengcn/TAICHI-flet#14]
1.安装了python3
2.然后 pip3 install -r requirements.txt
3.chmod +x ui.py
4.python3 ./ui.py

能弹出ui的窗口，但是里面一片黑色。
![3](https://user-images.githubusercontent.com/5109711/212441475-3237f2a9-e3b9-45cb-8937-02576484fbff.png)
![2](https://user-images.githubusercontent.com/5109711/212441482-23622ee6-f1c9-40db-9fab-5d851722e7ef.png)
![1](https://user-images.githubusercontent.com/5109711/212441485-7f747065-dd17-4254-a804-d5eda9b4af68.png)

**Comment by what2003** [comment]
pip3 install requests_html
