### ISSUE TITLE
大佬，可以在修仙里面完善一下基础功能吗？

### ISSUE THREAD

**Issue by ScottNotOG** [cuifengcn/TAICHI-flet#15]
需求是修改字体的类型、大小、间距等，字太小看着眼睛不舒服。
修改背景颜色，黑白对比度太刺眼，要是能有微软雅黑，配合护眼绿色背景，就太棒啦

**Comment by cuifengcn** [comment]
新版本加上调整字体、大小、间距、前景色、背景色的功能了
