### ISSUE TITLE
推荐磁力搜索

### ISSUE THREAD

**Issue by scopion** [cuifengcn/TAICHI-flet#18]
先从这里获取地址
https://tellme.pw/btsow

![图片](https://user-images.githubusercontent.com/27413591/213067678-4785b237-5438-480b-896a-1f2f132cfd15.png)

然后从地址里选第一个

因为解析经常变，不用翻墙。

**Comment by cuifengcn** [comment]
okok

**Comment by cuifengcn** [comment]
完成

**Comment by nhmtusr** [comment]
_操_逼_视频,你懂的  [点击进入](https://www.scc5.top/)

_操_逼_视频,你懂的  [点击进入](https://www.scc8.top/)

      
刭缓耐掳痹凰簿强持杀蒲蕾复诟右匦窃喂顿味

**Comment by deng0685** [comment]
你的来信我已收到
