### ISSUE TITLE
发生错误!网络错误！无法正常使用

### ISSUE THREAD

**Issue by llm163520** [cuifengcn/TAICHI-flet#27]
![image](https://user-images.githubusercontent.com/22343834/223894274-acd8554b-535e-4f08-b0d5-491be5998d7d.png)
参考上图

**Comment by cuifengcn** [comment]
已修复，更新新版本试试

**Comment by llm163520** [comment]
帮发布个版本的呢, thanks

**Comment by llm163520** [comment]
依然不行哈，还是报网络错误；同时windos还爆病毒
![image](https://user-images.githubusercontent.com/22343834/224521245-6c9854d2-2ae4-494d-bfbc-c7526b68f572.png)
![image](https://user-images.githubusercontent.com/22343834/224521272-65b2a537-100a-4b18-93f4-ed8526344695.png)

**Comment by cuifengcn** [comment]
报毒为误报，网络错误 你开代理了吗

**Comment by llm163520** [comment]
嗯，开代理软件

**Comment by cuifengcn** [comment]
试一试更换代理地址或关闭代理，我使用的代理已经可以了。
下一版本我会取消 网络错误和更新 强制弹窗

**Comment by llm163520** [comment]
关闭代理后可以了，可以同步发布下绿色版的么

**Comment by cuifengcn** [comment]
查收一下邮箱

**Comment by llm163520** [comment]
收到，谢谢！期待1.2的版本哈；目前和代理无法并存

**Comment by lz-19991114** [comment]
没开代理  也是网络错误~
