### ISSUE TITLE
公众号无法关注

### ISSUE THREAD

**Issue by Tobeprmn** [cuifengcn/TAICHI-flet#33]
“该公众号因违规无法关注”
![7LISGP%QERO6(ER(`TS4(32](https://user-images.githubusercontent.com/119318291/226310737-c98bf02c-ba66-4287-a8db-3060079e228c.png)

**Comment by weizhao911** [comment]
用不了啊

**Comment by justinyx** [comment]
![image](https://user-images.githubusercontent.com/8775576/226609274-8375b848-d444-4542-84fc-6648f979d867.png)
无法进入
