### ISSUE TITLE
file no found (taichi_db.dbm.dat)

### ISSUE THREAD

**Issue by JureQzy** [cuifengcn/TAICHI-flet#49]
打开软件后显示
There was an error while processing your request:[Error 2]No such file or directory:C:\\User\\myusername\\AppData\\Roaming\\taichi\\taichi_db.dbm.dat
版本是太极2.6.9
![QQ图片20230922114930](https://github.com/cuifengcn/TAICHI-flet/assets/145738048/41d0e96c-7b93-4d97-a37c-9746b9b13298)

**Comment by cuifengcn** [comment]
可以提供更详细的信息吗，系统版本，系统用户，方便排查。另外尝试手动创建缺失文件能否解决

**Comment by JureQzy** [comment]
恩
&nbsp; &nbsp; WIN11系统&nbsp; 64位&nbsp; &nbsp;系统用户名 a&nbsp;&nbsp;
&nbsp; &nbsp; 因为看缺失的是数据库文件,手动创建空文件应该也是没用的,而且没有该文件.&nbsp; 百度上查询这个文件也未果
&nbsp; &nbsp; 现在安装了2.6.5版本,看到正确创建了C:\Users\a\AppData\Roaming\taichi\shared_preferences.json&nbsp;&nbsp;可正常运行









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuifengcn/TAICHI-flet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月22日(星期五) 中午12:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuifengcn/TAICHI-flet] file no found (taichi_db.dbm.dat) (Issue #49)





 
可以提供更详细的信息吗，系统版本，系统用户，方便排查。另外尝试手动创建缺失文件能否解决

**Comment by cuifengcn** [comment]
上面的报错是]No such file or directory，可以试着手动创建来跳过这个问题的。另外此问题出现的原因是：2.6.7之后的版本使用轻量级数据库存储大文件数据，可能是因为系统权限原因导致相应文件创建失败

**Comment by JureQzy** [comment]
刚才尝试了下,在2.6.5版本中使用软件中的更新功能更新到2.6.9后,这些数据库文件都被正确创建了. 旧版本更新到新版本可以


之前新安装,运行exe的时候尝试给过管理员权限,但也创建失败





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuifengcn/TAICHI-flet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月22日(星期五) 中午12:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuifengcn/TAICHI-flet] file no found (taichi_db.dbm.dat) (Issue #49)





 
上面的报错是]No such file or directory，可以试着手动创建来跳过这个问题的。另外此问题出现的原因是：2.6.7之后的版本使用轻量级数据库存储大文件数据，可能是因为系统权限原因导致相应文件创建失败

**Comment by cuifengcn** [comment]
taichi文件夹未创建导致其中的数据库文件创建失败，已修复
