### ISSUE TITLE
你好，可以提供完整的源码吗？clone下来的没有run.py文件

### ISSUE THREAD

**Issue by 741148263** [cuifengcn/TAICHI-flet#5]

**Comment by yulk** [comment]
同问。

**Comment by yulk** [comment]
从大佬的帖子里找到了一个run.py。可用。
https://www.52pojie.cn/thread-1733154-1-1.html

**Comment by cuifengcn** [comment]
不好意思哇，写错了，不是run,py，运行ui.py就可以，源码是全的。

**Comment by 741148263** [comment]
好的，谢谢！新的flet库空了学一学，才出来没多久
