### ISSUE TITLE
Mac 的解决办法

### ISSUE THREAD

**Issue by Jeremy-JYL** [cuifengcn/TAICHI-flet#67]
我的方法就是, 使用Whisky 或者WINE，Mac上安装。

**Comment by deng0685** [comment]
你的来信我已收到

**Comment by Jeremy-JYL** [comment]
While quick translate: My solution is basically install Whisky or WINE and open with Whisky or WINE

**Comment by Jeremy-JYL** [comment]
https://getwhisky.app/

**Comment by Jeremy-JYL** [comment]
但是的安装中文包
